destination: ./_public
includes_dir: _includes

title: Principles, by a11y.rocks
description: >- # this means to ignore newlines until "baseurl:"
  How companies break accessibility principles
baseurl: ""
url: "https://principles.a11y.rocks"
github: "https://github.com/a11yrocks/"
github_repo: "https://github.com/a11yrocks/principles"
markdown: kramdown
plugins:
  - jekyll-feed
permalink: /report/:path
compress_html:
  clippings: all
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/css/
  - postcss.config.js
  - yarn.lock
  - package.json
  - package-lock.json
